spring.application.name=demo
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.collection-name=nflrules
spring.docker.compose.stop.command=down
spring.docker.compose.stop.arguments=--volumes

spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

app.resource=classpath:/spring-boot-reference.pdf